wandb_version: 1

batch_size:
  desc: null
  value: 28
epoch:
  desc: null
  value: 60
embedding:
  desc: null
  value: nn.Linear
Type:
  desc: null
  value: DDDDAA
Block_size:
  desc: null
  value: bigger
Resume:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1716737196.0
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 71
      - 83
      3:
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.16.6
      8:
      - 2
      - 5
      13: linux-x86_64
